[package]
name = "gbm"
description = "libgbm bindings for rust"
license = "MIT"
documentation = "https://docs.rs/gbm"
repository = "https://github.com/Smithay/gbm.rs"
version = "0.5.0"
keywords = ["wayland", "gbm", "drm", "bindings"]
categories = ["external-ffi-bindings"]
authors = ["Victor Brekenfeld <github@drakulix.de>"]
exclude = [".travis.yml", ".rustfmt.toml"]

[dependencies]
gbm-sys = { version = "0.1", path = "./gbm-sys" }
libc = "0.2.66"
bitflags = "1.2.1"
wayland-client = { version = "0.23", optional = true }
drm = { version = "0.3.4", optional = true }
glutin_interface = { version = "0.1.0", path = "../glutin_interface", optional = true }
winit_types = { version = "0.1.0", path = "../winit_types", optional = true }

[dev-dependencies]
drm = "0.3.4"

[features]
default = ["import-wayland", "import-egl", "drm-support", "glutin-support"]
glutin-support = ["glutin_interface", "winit_types"]
import-wayland = ["wayland-client"]
import-egl = []
drm-support = ["drm"]
gen = ["gbm-sys/gen"]
